# https://travis-ci.org/kecnry/nparray

language: python

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

dist: trusty

env:
    global:
        # Set defaults to avoid repeating in most cases
        - PIP_DEPENDENCIES='nose'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try with default version of numpy/astropy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0'

        - os: osx
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0'

        # Try with various versions of numpy/astropy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=stable ASTROPY_VERSION=2.0'

        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=stable ASTROPY_VERSION=stable'

    allow_failures:
      - env: NUMPY_VERSION=dev


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py build
    - python setup.py install --user

script:
    - nosetests -v -s -d -w tests/;
